# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Pitts
email: ampcodes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming, development, terrible jokes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andrewmpitts.github.io" # the base hostname & protocol for your site
twitter_username: andrewpitts
github_username:  andrewmpitts
about: Andrew Pitts is a programmer and teacher in the foothills of North Carolina. If you wish to contact him regarding code or offers of work, he can be reached <a href = "mailto:ampcodes@gmail.com">here</a>.
# Build settings
markdown: kramdown
